import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'agent-skills',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/parse-project',
        'guides/file-rules',
        'guides/class-rules',
        'guides/function-rules',
        'guides/property-rules',
        'guides/layered-architecture',
        'guides/slices',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api', // Points to docs/api
        },
      ],
    },
  ],
};

export default sidebars;
